### ISSUE TITLE
UI: open links in new browser tab/window not possible

### ISSUE THREAD

**Issue by anbrsap** [InfraBox/infrabox#318] opened 2018-04-23 07:11 UTC
It's common practice to open pages of a Web UI in new browser windows/tabs.

Trying this with the Infrabox UI leads to error message "unauthorized".

**Comment by ib-steffen** [comment] 2018-04-23 09:15
Which link did you open and which browser did you use?
I can open links in new tabs in firefox/chrome.

**Comment by anbrsap** [comment] 2018-04-23 11:13
I cannot repoduce it anymore. I've been using Chrome 66.0.3359.117 64-Bit Windows, and I've tried the link to a project from the menu (`/dashboard/#/project/<project_name>`).

**Comment by ib-steffen** [comment] 2018-04-23 11:16
I close the issue as we both cannot reproduce it anymore. Please re-open if it happens again.

**Closed by ib-steffen** 2018-04-23 11:16 UTC
